
export const IdArray = [
    {
        
        id: '#0211',
                imgSrcuper: 'Rectangle 13.png',
        imgSrcdown: 'Rectangle 15.png',
        headertext: 'Expired',
        icon: 'far fa-ban',
        price:'CLOSE PRICE',
        background: 'card-header bg-light text-muted',
        Bottomtext: 'text-white text-center fs-5',
        bottomtextP: 'text-white text-center',
        Upertext: 'text-success text-center fs-5',
        UpertextP: 'text-dark text-center mb-2',
        iconarrow:'far fa-arrow-down',
        btncenter:'btn btn-danger btn-sm bodybutton011',
        csscheck: 'backgroundColor:"red"',
        display1:'show',
        display2:'d-none',
        bar:'d-none',
        display3:'d-none',
        display5:'d-none',


    },
    {
        
        id: '#6421',
                imgSrcuper: 'Rectangle 13.png',
        imgSrcdown: 'Rectangle 15.png',
        headertext: 'Expired',
        icon: 'far fa-ban',
        background: 'card-header bg-light text-muted',
        Bottomtext: 'text-white text-center fs-5',
        bottomtextP: 'text-white text-center',
        Upertext: 'text-success text-center fs-5',
        UpertextP: 'text-dark text-center mb-2',
        iconarrow:'far fa-arrow-down',
        btncenter:'btn btn-danger btn-sm bodybutton011',
        csscheck: 'backgroundColor:"red"',
        price:'CLOSE PRICE',
        display1:'show',
        display2:'d-none',bar:'d-none',
        display3:'d-none',
        display5:'d-none',


    },
    {
        id: '#1242',
        imgSrcuper: 'Rectangle 19.png',
        imgSrcdown: 'Rectangle 20.png',
        headertext: 'Live',
        headertextclass:'text-primary mb-5',
        icon: 'far fa-play-circle fs-5 mt-1 text-primary',
        background: 'card-header bg-light text-muted',
        Bottomtext: 'text-danger text-center fs-5',
        bottomtextP: 'text-dark text-center',
        Upertext: 'text-w text-center fs-5',
        UpertextP: 'text-white text-center',
        iconarrow:'far fa-arrow-up',
        btncenter:'btn btn-success btn-sm bodybutton011',
        price:'LAST PRICE',
        display1:'show',
        display2:'d-none',
        bar:'bar',
        display3:'d-none',
        display5:'d-none',

    },
    {
        id: '#1253',
        imgSrcuper: 'Rectangle 13.png',
        imgSrcdown: 'Rectangle 15.png',
        headertext: 'Next',
       icon: 'far fa-play-circle fs-5 mt-1',
        background: ' card-header bg-primary text-white',
        Bottomtext: 'text-white text-center fs-5',
        bottomtextP: 'text-white text-center',
        Upertext: 'text-success text-center fs-5',
        UpertextP: 'text-dark text-center',
        iconarrow:'far fa-arrow-down',
        btncenter:'btn btn-danger btn-sm bodybutton011', price:'LAST PRICE',
        display1:'d-none',
        display2:'none',bar:'d-none',
        display3:'d-none',
        display5:'d-none',

    },
    
    {
        id: '#1254',
        imgSrcuper: 'Rectangle 13.png',
        imgSrcdown: 'Rectangle 20.png',       
        headertext: 'Later',
       icon: 'far fa-play-circle fs-5 mt-1',
        background: ' card-header bg-Dark text-muted',
        Bottomtext: 'text-secondary text-center fs-5 mt-3',
        bottomtextP: 'text-white text-center d-none',
        Upertext: 'text-secondary text-center fs-5 mt-3',
        UpertextP: 'text-dark text-center d-none',
        iconarrow:'far fa-arrow-down',
        btncenter:'btn btn-danger btn-sm bodybutton011',
        price:'LAST PRICE',
        display1:'d-none',
        display2:'d-none',
        bar:'d-none',
        display3:'show',
        display5:'d-none',

    },
    {
        id: '#1404',
        imgSrcuper: 'Rectangle 13.png',
        imgSrcdown: 'Rectangle 20.png',
        headertext: 'Later',
       icon: 'far fa-play-circle fs-5 mt-1',
        background: ' card-header bg-Dark text-muted',
        Bottomtext: 'text-secondary text-center fs-5 mt-3 ',
        bottomtextP: 'text-white text-center d-none',
        Upertext: 'text-secondary text-center fs-5 mt-3',
        UpertextP: 'text-dark text-center d-none ',
        iconarrow:'far fa-arrow-down',
        btncenter:'btn btn-danger btn-sm bodybutton011',
        price:'LAST PRICE',
        display1:'d-none',
        display2:'d-none',
        bar:'d-none',
        display3:'show',
        display5:'d-none',

    },

]    